# Install and test and OMERO plugin e.g. a Web app, a CLI plugin or a library
#
# This workflow will install omero-test-infra, start an OMERO environment
# including database, server and web deployment, configure the OMERO plugin
# and run integration tests.
#
# 1. Set up the stage variable depending on the plugin. Supported stages
# are: app, cli, scripts, lib, srv
#
# 2. Adjust the cron schedule as necessary

name: OMERO Plugin
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-20.04
    env:
      STAGE: srv # app, cli, lib, scripts, srv
    steps:
      - uses: actions/checkout@v2
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Set up log level
        run: |
          echo 'ivy.retrieve.log=default' >> etc/local.properties
      #- name: Build and run OMERO tests
      #  run: .omero/docker $STAGE
